const commands = {
    '/help': () => [
      'PORTFOLIO TERMINAL - COMMAND REFERENCE',
      '======================================',
      '',
      'Navigation Commands:',
      '  /gui        - Launch Windows 98 GUI interface',
      '  /about      - Display personal information',
      '  /skills     - List technical skills',
      '  /projects   - Show project portfolio',
      '  /contact    - Display contact information',
      '',
      'System Commands:',
      '  /clear      - Clear terminal screen',
      '  /help       - Show this help message',
      '  /exit       - Return to boot screen',
      '  /skip       - Skip to GUI (same as /gui)',
      '',
      'Tip: Type "/gui" to access the graphical interface!',
      'Most users prefer the GUI for easier navigation.'
    ],
    '/gui': () => 'LAUNCH_GUI',
    '/skip': () => 'LAUNCH_GUI',
    '/about': () => [
      '=====================================',
      '           USER PROFILE v1.2         ',
      '=====================================',
      '',
      'Name: Fernando Murra Vicario',
      'Title: Full Stack Developer',
      'Location: San Antonio, TX',
      'Experience: 3+ years',
      '',
      'Bio: Passionate developer specializing in modern',
      'web technologies. Expert in creating scalable',
      'applications and solving complex problems.',
      '',
      'Education: B.S. Computer Science & Business',
      'University: Washington University in St.Louis (2028)',
      '',
      'Type "/gui" to see this in a prettier format!'
    ],
    '/skills': () => [
      'TECHNICAL SKILLS DATABASE',
      '========================',
      '',
      '[PROGRAMMING LANGUAGES]',
      '  Java................. [██████████░░] Advanced',
      '  Python............... [██████████░░] Skilled',
      '  TypeScript........... [████████░░░░] Intermediate',
      '  JavaScript........... [████████░░░░] Intermediate',
      '',
      '[FRAMEWORKS & LIBRARIES]',
      '  React................ [████████░░░░] Intermediate',
      '  Node.js.............. [███████████░] Skilled',
      '  Express.............. [████████░░░░] Intermediate',
      '  Vue.js............... [██████████░░] Skilled',
      '',
      'Type "/gui" for an interactive skills view!'
    ],
    '/projects': () => [
      'PROJECT REPOSITORY',
      '==================',
      '',
      '[1] BatteryFinder',
      '    Tech: React Native, Node.js, Supabase',
      '    Status: DEPLOYED',
      '',
      '[2] Genie Chrome Extension',
      '    Tech: Gemini, JavaScript, Render',
      '    Status: MAINTAINED',
      '',
      '[3] Group Chat',
      '    Tech: HTML, Python, APIs',
      '    Status: ACTIVE',
      '',
      'Type "/gui" to see detailed project showcases!'
    ],
    '/contact': () => [
      'CONTACT INFORMATION',
      '===================',
      '',
      'Email: fmuvic13@email.com',
      'LinkedIn: linkedin.com/in/fernando-murra-vicario-/',
      'GitHub: github.com/F-MurraVicario13',
      'Portfolio: fernandomurra.com',
      '',
      'Type "/gui" for interactive contact options!'
    ],
    '/clear': () => 'CLEAR',
    '/exit': () => 'EXIT'
  };
  
  export default commands;
  