const commands = {
  '/help': () => [
    'PORTFOLIO TERMINAL - COMMAND REFERENCE',
    '======================================',
    '',
    'Navigation Commands:',
    '  /gui        - Launch Windows 98 GUI interface',
    '  /about      - Display personal information',
    '  /skills     - List technical skills',
    '  /projects   - Show current desktop project inventory',
    '  /contact    - Display contact information',
    '',
    'System Commands:',
    '  /clear      - Clear terminal screen',
    '  /help       - Show this help message',
    '  /exit       - Return to boot screen',
    '  /skip       - Skip to GUI (same as /gui)',
    '',
    'Desktop Notes:',
    '  Each project now opens as its own icon/window in the GUI.',
    '  Use /gui if you want the full retro desktop experience.'
  ],
  '/gui': () => 'LAUNCH_GUI',
  '/skip': () => 'LAUNCH_GUI',
  '/about': () => [
    '=====================================',
    '           USER PROFILE v1.3         ',
    '=====================================',
    '',
    'Name: Fernando Murra Vicario',
    'Title: Full Stack Developer',
    'Location: San Antonio, TX',
    'Focus: Software Development, Cybersecurity, Data',
    '',
    'Bio: I like building useful products with a bit of',
    'personality. This portfolio uses a retro OS shell,',
    'but the goal is simple: show how I build and think.',
    '',
    'Type "/gui" to open the desktop version.'
  ],
  '/skills': () => [
    'TECHNICAL SKILLS DATABASE',
    '=========================',
    '',
    '[PROGRAMMING LANGUAGES]',
    '  Java................. [██████████░░] Advanced',
    '  Python............... [██████████░░] Skilled',
    '  TypeScript........... [█████████░░░] Intermediate',
    '  JavaScript........... [█████████░░░] Intermediate',
    '',
    '[FRAMEWORKS & LIBRARIES]',
    '  React................ [█████████░░░] Intermediate',
    '  Node.js.............. [███████████░] Skilled',
    '  Express.............. [████████░░░░] Intermediate',
    '  HTML/CSS............. [██████████░░] Skilled',
    '',
    '[TOOLS]',
    '  Git, Docker, AWS, Linux, Postman, VS Code',
    '',
    'Type "/gui" for the visual skills window.'
  ],
  '/projects': () => [
    'PROJECT REPOSITORY',
    '==================',
    '',
    '[1] GroupChat',
    '    Tech: HTML, Python, APIs',
    '    Status: ACTIVE',
    '',
    '[2] Genie Chrome Extension',
    '    Tech: Gemini, JavaScript, Render',
    '    Status: MAINTAINED',
    '',
    '[3] Super Mario DQN',
    '    Tech: Python, DQN, Reinforcement Learning',
    '    Status: RESEARCH',
    '',
    '[4] Book Review',
    '    Tech: Python, Data, Web App',
    '    Status: ACTIVE',
    '',
    '[5] Heat Map',
    '    Tech: Data Viz, Python, Analytics',
    '    Status: ACTIVE',
    '',
    '[6] ESG Pipeline',
    '    Tech: Python, Pipelines, Data Engineering',
    '    Status: PIPELINE',
    '',
    'Type "/gui" to open each one as its own desktop icon.'
  ],
  '/contact': () => [
    'CONTACT INFORMATION',
    '===================',
    '',
    'Email: fmuvic13@gmail.com',
    'LinkedIn: linkedin.com/in/fernando-murra-vicario-/',
    'GitHub: github.com/F-MurraVicario13',
    'Resume: available from the GUI desktop',
    '',
    'Type "/gui" for interactive contact options.'
  ],
  '/clear': () => 'CLEAR',
  '/exit': () => 'EXIT'
};

export default commands;
